# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title-bold: DanTheGeekMan
# title-normal: by HTML5 UP
email: dan@danthegeekman.com
description: I am a Junior Web Developer and this is my portfolio.  Get a mug of coffee and have a look around ;-)
# baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
baseurl: "/portfolio"
url: "" # the base hostname & protocol for your site
author: Dan Rogers
# street_address: 1234 Somewhere Road
# city: Nashville
# state: TN
# zip_code: 55555
# country: United States of America
# phone: (716) 555-5555

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 4

# Social settings
500px_url:
facebook_url:
github_url:     https://github.com/DanTheGeekMan
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:   https://www.linkedin.com/in/DanTheGeekMan
pinterest_url:
slack_url:
twitter_url:    https://twitter.com/DanTheGeekMan

# Build settings
markdown: kramdown

# Plugin: jekyll-seo-tag
twitter:
  username: andrewbanchich
# Add one or more of the following
facebook:
  app_id:
  publisher:
  admins:
logo:
google_site_verification:
